
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author 18299
 */
public class Partidos extends javax.swing.JInternalFrame {
    boolean creando = true;
    /**
     * Creates new form Partidos
     */
    public Partidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        votos = new javax.swing.JTextField();
        estado = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mantenimiento de Partidos");

        jLabel1.setText("ID");

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripción");

        jLabel4.setText("Votos");

        estado.setForeground(new java.awt.Color(255, 0, 0));
        estado.setText("CREANDO");
        estado.setCaretColor(new java.awt.Color(255, 0, 0));
        estado.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        estado.setEnabled(false);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(votos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(Guardar)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(votos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        String mid = id.getText();
        if(mid.isEmpty()){
            JOptionPane.showMessageDialog(null, "El ID es obligatorio.");
            return;
        }
        String mdesc = desc.getText();
        if(mdesc.isEmpty()){
            JOptionPane.showMessageDialog(null, "La descripcion es obligatoria.");
            return;
        }
        String mvotos = votos.getText();
        if(mvotos.isEmpty()){
            JOptionPane.showMessageDialog(null, "Los votos son obligatorios.");
            return;
        }
        
        if(creando == true){
            File f = new File("C:partidos.txt");
            
            try{
                if(!f.exists()){
                    f.createNewFile();
                }
                BufferedReader br = new BufferedReader(new FileReader(f));
                BufferedWriter bw = new BufferedWriter(new FileWriter("C:partidos.txt"));
                
                bw.write(mid + " ; " + mdesc + " ; " + mvotos);
                
                bw.flush();
                
            }catch(IOException ex){
                System.out.println("Error E/S: "+ex);
            }
        }else{
            File fnuevo = new File("C:partidos1.txt");
            File fantiguo = new File("C:partidos.txt");
            
            String acadena = (mid + " ; " + mdesc + " ; " + mvotos);
            String bcadena = (mid + " ; " + mdesc + " ; " + mvotos);
            int aid = Integer.parseInt(mid);
            
            BufferedReader br;
            
            try{
                if(fantiguo.exists()){
                    br = new BufferedReader(new FileReader(fantiguo));
                    String linea;
                    
                    Scanner s = new Scanner(fantiguo);
                    while(s.hasNextLine()){
                        linea = s.nextLine();
                        Scanner sl = new Scanner(linea);
                        
                        sl.useDelimiter("\\s*;\\s*");
                        int bid = Integer.parseInt(sl.next());
                        
                        if(aid==bid){
                            BufferedWriter bw = new BufferedWriter(new FileWriter("C:partidos1.txt"));
                            bw.write(mid + " ; " + mdesc + " ; " + mvotos);
                        }else{
                            BufferedWriter bw = new BufferedWriter(new FileWriter("C:partidos1.txt"));
                            bw.write(linea);
                        }
                        
                    }//fin whilw
                    s.close();
                    
                    String nomantiguo = fantiguo.getName();
                    
                    //metodo borrar
                    fantiguo.delete();
                    fnuevo.renameTo(fantiguo);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Partidos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Partidos.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        estado.setText("CREANDO");
        id.setText("");
        desc.setText("");
        votos.setText("");
        

    }//GEN-LAST:event_GuardarActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        int mid;
        boolean creando = false;
        
        mid = Integer.parseInt(id.getText());
        
        Scanner s;
        
        try{
            File f = new File("C:partidos.txt");
            s = new Scanner(f);
            
            if(!f.exists()){
                f.createNewFile();
            }else{
                while (s.hasNextLine() && !creando){
                    String linea = s.nextLine();
                    Scanner sl = new Scanner(linea);
                    
                    sl.useDelimiter("\\s*;\\s*");
                    if(mid == Integer.parseInt(sl.next())){
                        desc.setText(sl.next());
                        votos.setText(sl.next());
                        creando = true;
                        
                        estado.setText("MODIFICANDO");
                        
                    }else{
                        creando = false;
                        
                        estado.setText("CREANDO");
                    }
                    
                }
                    
            }
            s.close();
        
        }catch(IOException e1){
            e1.printStackTrace();
        }
        
    }//GEN-LAST:event_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        dispose();
        //System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        estado.setText("CREANDO");
        id.setText("");
        desc.setText("");
        votos.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField desc;
    private javax.swing.JTextField estado;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField votos;
    // End of variables declaration//GEN-END:variables
}
